### ISSUE TITLE
Screen freezes everytime the UI reloads

### ISSUE THREAD

**Issue by xyz1hang** [Peterodox/YUI-Dialogue#84]
Amazing addon. Absolutely love it.

Not sure why but every time the UI loads (teleport, in or out of dungeon, raid etc.) the screen freezes for around 3 seconds.

Tried disable all other addon and still the case.

I am on 11.0.5 retail and using RTX 4070

**Comment by Peterodox** [comment]
Thank you :)
Have you tried disabling all addons including this one?

**Comment by xyz1hang** [comment]
> Thank you :)
> Have you tried disabling all addons including this one?

Lol, well before installing this addon there's no such issue. What could be the the causes? 1-3 second game freeze

**Comment by Peterodox** [comment]
The cross-faction, cross-server tech has taken a toll on WoW's stability. There have been lots of reports of game freezing since the pre-patch. Here are some from the last 24 hours:
 https://eu.forums.blizzard.com/en/wow/t/freezing-after-a-loading-screen-recent-bug/548251
https://eu.forums.blizzard.com/en/wow/t/5-10-seconds-freeze-after-loading-screen/548390
https://us.forums.blizzard.com/en/wow/t/5-10-seconds-freeze-after-loading-screen/2005891

I suggest disabling/re-enabling this addon to see if it makes a difference.

**Comment by xyz1hang** [comment]
Indeed ...

This addon is what wow dev should had done. Good job !
